//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly : AssemblyProduct("BinaryComponents")]
[assembly : AssemblyCompany("BinaryComponents Ltd")]
[assembly : AssemblyTitle("BinaryComponents.SuperList")]
[assembly : AssemblyDescription("BinaryComponents List Control")]
[assembly : AssemblyCopyright("Copyright © BinaryComponents Ltd 2005-2006")]
[assembly : ComVisible(false)]
[assembly : CLSCompliant(true)]
[assembly : AssemblyVersion("1.0.259.0")]
[assembly : AssemblyFileVersion("1.0.259.0")]